### ISSUE TITLE
Pdf for Version 4.2

### ISSUE THREAD

**Issue by hengxin** [mietek/software-foundations#3]
The latest version is [4.2 (Spring, 2017)](https://softwarefoundations.cis.upenn.edu/current/index.html).
Are you going to update it?

**Comment by marsam** [comment]
FWIW I've build the recent version with nix: https://gitlab.com/marsam/software-foundations, you can download the pdfs from https://gitlab.com/marsam/software-foundations/-/jobs/39122761/artifacts/browse

**Comment by renovatorruler** [comment]
@marsam your pdf has order of the chapters inverted
