### ISSUE TITLE
File "./LibTactics.v", line 3187, characters 17-18: Error: Syntax error: ')' expected after [constr:lconstr] (in [tactic:tactic_arg]).

### ISSUE THREAD

**Issue by tiansiyuan** [mietek/software-foundations#5]
make
"coqc"  -q  -I .    LibTactics
File "./LibTactics.v", line 3187, characters 17-18:
Error:
Syntax error: ')' expected after [constr:lconstr] (in [tactic:tactic_arg]).

make: *** [LibTactics.vo] Error 1

On macOS

**Comment by mietek** [comment]
I’m sorry. This mirror has not been maintained. However, as of today, it is up-to-date.
